[package]
edition = "2021"
name = "ui_service"
version = "0.1.0"

[dependencies]
axum = "0.6"
axum-server = {version = "0.4", features = ["tls-rustls"]}
dev_util = "0.1"
lazy_static = "1.4"
log = "0.4"
serde_json = "1.0"
tokio = {version = "1", features = ["full"]}
